export function capitalize(string: string) {
    const firstLetter = string.charAt(0).toUpperCase();
    const otherLetters = string.slice(1);

    return firstLetter + otherLetters;
}

export function levenshteinDistance(a: string, b: string) {
    // Generated by ChatGPT

    const aLen = a.length;
    const bLen = b.length;

    const dp: number[][] = [];
    for (let i = 0; i <= aLen; i++) {
        dp[i] = new Array(bLen + 1);
    }

    for (let i = 0; i <= aLen; i++) {
        for (let j = 0; j <= bLen; j++) {
            if (i === 0) {
                dp[i][j] = j;
            } else if (j === 0) {
                dp[i][j] = i;
            } else {
                const cost = a[i - 1] === b[j - 1] ? 0 : 1;
                dp[i][j] = Math.min(
                    dp[i - 1][j] + 1,
                    dp[i][j - 1] + 1,
                    dp[i - 1][j - 1] + cost
                );
            }
        }
    }

    return dp[aLen][bLen];
}
